export const COURSES = [
  {
    name: "Python Programming for Beginners",
    description: "Basics of coding in Python language",
    slug: "beginners-python-programming",
    image: "/_temp/programming_with_python-MHbd2g.png",
    level: 0,
    lessonsCount: 7,
    category: {
      name: "Computer Science",
      description: "Algorithms and coding",
      slug: "computer-science",
    },
    lessons: [
      {
        name: "Welcome to Python",
        description: "Get off the ground with your first Python functions.",
        slug: "welcome-to-python",
        unit: 1,
        part: 1,
        duration: 30,
        content: "",
      },
      {
        name: "Practice Welcome to Python",
        description: "Cement your understanding of Welcome to Python",
        slug: "practice",
        unit: 1,
        part: 2,
        duration: 45,
        content: "",
      },
      {
        name: "Numbers in Python",
        description: "See how Python handles different types of data.",
        slug: "python-data-types",
        unit: 1,
        part: 3,
        duration: 20,
        content: "",
      },
      {
        name: "Practice Numbers in Python",
        description: "Cement your understanding of Numbers in Python",
        slug: "pypractice12-v0-set_one",
        unit: 2,
        part: 4,
        duration: 15,
        content: "",
      },
      {
        name: "Variables in Python",
        description: "Start storing data and manipulating numbers.",
        slug: "variables-and-math",
        unit: 2,
        part: 5,
        duration: 35,
        content: "",
      },
      {
        name: "Algebra",
        description: "Cement your understanding of Variables in Python",
        slug: "algebra-first-lesson",
        unit: 3,
        part: 6,
        duration: 40,
        content: "",
      },
      {
        name: "Conversion Challenge",
        description: "Use what you've learned to tackle your first challenge.",
        slug: "conversion-challenge-2",
        unit: 3,
        part: 7,
        duration: 25,
        content: "",
      },
    ],
  },
  {
    name: "Astronomy 101",
    description: "Planetary motion and celestial objects",
    slug: "astronomy-101",
    image: "/_temp/astronomy-vi1jpD.png",
    level: 0,
    lessonsCount: 0,
    category: {
      name: "Astronomy",
      description: "Celestial bodies and phenomena",
      slug: "astronomy",
    },
    lessons: [],
  },
  {
    name: "Anatomy and Physiology",
    description: "Structure and function of the human body",
    slug: "anatomy-and-physiology",
    image: "/_temp/Molecules-nHpvAL.png",
    level: 0,
    lessonsCount: 0,
    category: {
      name: "Medicine",
      description: "Health and anatomy",
      slug: "medicine",
    },
    lessons: [],
  },
  {
    name: "Robotics Fundamentals",
    description: "Basics of robot design and control",
    slug: "robotics-fundamentals",
    image: "/_temp/classical_mechanics-JYFpGo.png",
    level: 0,
    lessonsCount: 0,
    category: {
      name: "Robotics",
      description: "Automation and mechanics",
      slug: "robotics",
    },
    lessons: [],
  },
  {
    name: "Introduction to Genetics",
    description: "Principles of inheritance and genetic variation",
    slug: "genetics-intro",
    image: "/_temp/Computational_Biology-I9yy6t.png",
    level: 1,
    lessonsCount: 12,
    category: {
      name: "Biology",
      description: "Life forms and systems",
      slug: "biology",
    },
    lessons: [],
  },
  {
    name: "Introduction to Electrical Engineering",
    description: "Circuits and basic electronics",
    slug: "electrical-engineering-intro",
    image: "/_temp/electricity_and_magnetism-rJijqR.png",
    level: 0,
    lessonsCount: 0,
    category: {
      name: "Engineering",
      description: "Design and innovation",
      slug: "engineering",
    },
    lessons: [],
  },
  {
    name: "Introduction to Environmental Science",
    description: "Ecosystems and environmental issues",
    slug: "environmental-science-intro",
    image: "/_temp/Brilliant-Kurzgesagt_Logo_02_1_1-o6XxYQ.png",
    level: 0,
    lessonsCount: 0,
    category: {
      name: "Environmental Science",
      description: "Ecosystems and sustainability",
      slug: "environmental-science",
    },
    lessons: [],
  },
  {
    name: "Organic Chemistry Basics",
    description: "Molecular structures and reactions",
    slug: "organic-chemistry-basics",
    image: "/_temp/the_chemical_reaction-JsXxfp.png",
    level: 1,
    lessonsCount: 26,
    category: {
      name: "Chemistry",
      description: "Elements and reactions",
      slug: "chemistry",
    },
    lessons: [],
  },
  {
    name: "Classical Mechanics",
    description: "Newton's laws and motion equations",
    slug: "classical-mechanics",
    image: "/_temp/Quantum_Mechanics_with_Sabine-xyAhEq.png",
    level: 3,
    lessonsCount: 21,
    category: {
      name: "Physics",
      description: "Laws of motion and energy",
      slug: "physics",
    },
    lessons: [],
  },
  {
    name: "Introduction to Calculus",
    description: "Fundamental concepts of differentiation and integration",
    slug: "calculus-intro",
    image: "/_temp/calc_fundamentals_960_by_960-vQVufa.png",
    level: 2,
    lessonsCount: 14,
    category: {
      name: "Mathematics",
      description: "All mathematical basics",
      slug: "mathematics",
    },
    lessons: [],
  },
];
